version: '3.8'
services:
  stats-server:
    build: ./stats/server
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/exploreStats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/dataStats

    environment:
      - POSTGRES_DB=exploreStats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
    restart: on-failure
    depends_on:
      - ewm-db
      - stats-server
    ports:
      - "8080:8080"
    environment:
      - MAIN_SERVER_URL=http://ewm-server:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - POSTGRES_USER_MAIN=test
      - POSTGRES_PASSWORD_MAIN=test

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/ewm

    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test